// examples/weather/solid-nanostores/src/components/Forecast.tsx
/* eslint-disable @typescript-eslint/no-magic-numbers */
import { useStore } from '@nanostores/solid'
import {
  createSignal,
  createMemo,
  For,
  Show
} from 'solid-js'
import { $weatherForecast } from 'data-layer/stores/weather'
import { ForecastWeather } from './ForecastWeather.jsx'
import styles from './Forecast.module.css'

export function Forecast() {
  const weatherForecast = useStore($weatherForecast)
  const [mode, setMode] = createSignal<'hourly' | 'daily'>('hourly')
  const forecastToShow = createMemo(() => {
    const weatherForecastValue = weatherForecast()
    const modeValue = mode()

    return weatherForecastValue.filter(
      (_, index) => (modeValue === 'hourly' && index < 10) || (modeValue === 'daily' && index % 8 === 0)
    )
  })

  return (
    <Show when={forecastToShow().length > 0}>
      <section>
        <header class={styles.header}>
          <h2 class={styles.title}>Forecast</h2>
          <select
            class={styles.mode}
            value={mode()}
            onInput={e => setMode(e.currentTarget.value as 'hourly' | 'daily')}
          >
            <option value='hourly'>Hourly</option>
            <option value='daily'>Daily</option>
          </select>
        </header>
        <ul class={styles.list}>
          <For each={forecastToShow()}>
            {weather => (
              <ForecastWeather
                weather={weather}
                mode={mode()}
              />
            )}
          </For>
        </ul>
      </section>
    </Show>
  )
}

// examples/weather/react-nano_kit-di/src/components/Forecast.tsx
/* eslint-disable @typescript-eslint/no-magic-numbers */
import {
  useState,
  useMemo,
  useCallback
} from 'react'
import {
  useInject,
  useSignal
} from '@nano_kit/react'
import { WeatherForecast$ } from 'data-layer/stores/weather'
import { ForecastWeather } from './ForecastWeather.jsx'
import styles from './Forecast.module.css'

export function Forecast() {
  const { $forecast } = useInject(WeatherForecast$)
  const forecast = useSignal($forecast)
  const [mode, setMode] = useState('hourly')
  const forecastToShow = useMemo(
    () => forecast.filter(
      (_, index) => (mode === 'hourly' && index < 10) || (mode === 'daily' && index % 8 === 0)
    ),
    [forecast, mode]
  )
  const handleModeChange = useCallback(
    (e: React.ChangeEvent<HTMLSelectElement>) => setMode(e.target.value),
    []
  )

  if (forecast.length === 0) {
    return null
  }

  return (
    <section>
      <header className={styles.header}>
        <h2 className={styles.title}>
          Forecast
        </h2>
        <select
          className={styles.mode}
          value={mode}
          onChange={handleModeChange}
        >
          <option value='hourly'>
            Hourly
          </option>
          <option value='daily'>
            Daily
          </option>
        </select>
      </header>
      <ul className={styles.list}>
        {forecastToShow.map(weather => (
          <ForecastWeather
            key={weather.dateText}
            weather={weather}
            mode={mode}
          />
        ))}
      </ul>
    </section>
  )
}
