// examples/weather/solid-nanostores/src/components/Weather.tsx
import { useStore } from '@nanostores/solid'
import { Show } from 'solid-js'
import { $currentWeather } from 'data-layer/stores/weather'
import styles from './Weather.module.css'

export function Weather() {
  const currentWeather = useStore($currentWeather)

  return (
    <Show when={currentWeather()}>
      <div class={styles.root}>
        <h3 class={styles.currentTemp}>
          {currentWeather()!.tempText}
        </h3>
        <img
          class={styles.image}
          src={currentWeather()!.icon}
          alt={currentWeather()!.description}
        />
        <p
          class={styles.feelsLike}
        >
          Feels like {currentWeather()!.feelsLikeText}
        </p>
        <p class={styles.description}>
          {currentWeather()!.description}
          <br />
          Humidity: {currentWeather()!.humidity}%
        </p>
      </div>
    </Show>
  )
}

// examples/weather/react-nano_kit-di/src/components/Weather.tsx
import {
  useInject,
  useSignal
} from '@nano_kit/react'
import { CurrentWeather$ } from 'data-layer/stores/weather'
import styles from './Weather.module.css'

export function Weather() {
  const { $weather } = useInject(CurrentWeather$)
  const weather = useSignal($weather)

  if (!weather) {
    return null
  }

  return (
    <div className={styles.root}>
      <h3 className={styles.currentTemp}>
        {weather.tempText}
      </h3>
      <img
        className={styles.image}
        src={weather.icon}
        alt={weather.description}
      />
      <p className={styles.feelsLike}>
        Feels like
        {' '}
        {weather.feelsLikeText}
      </p>
      <p className={styles.description}>
        {weather.description}
        <br/>
        Humidity:
        {' '}
        {weather.humidity}
        %
      </p>
    </div>
  )
}
