// examples/weather/solid-nanostores/src/components/ForecastWeather.tsx
import {
  Switch,
  Match,
  splitProps
} from 'solid-js'
import type { Weather } from 'data-layer/services/types'
import styles from './ForecastWeather.module.css'

interface Props {
  weather: Readonly<Weather>
  mode: 'hourly' | 'daily'
}

export function ForecastWeather(props: Props) {
  const [local] = splitProps(props, ['weather', 'mode'])

  return (
    <div class={styles.root}>
      <time
        class={styles.time}
        dateTime={local.weather.dateText}
      >
        <Switch>
          <Match when={local.mode === 'hourly'}>
            {local.weather.date.toLocaleTimeString(undefined, {
              hour: 'numeric',
              minute: '2-digit'
            })}
          </Match>
          <Match when={local.mode === 'daily'}>
            {local.weather.date.toLocaleDateString(undefined, {
              day: 'numeric',
              month: 'short'
            })}
          </Match>
        </Switch>
      </time>
      <img
        class={styles.image}
        src={local.weather.icon}
        alt={local.weather.description}
      />
      <h3
        class={styles.temp}
      >
        {local.weather.tempText}
      </h3>
      <p class={styles.description}>
        {local.weather.description}
      </p>
    </div>
  )
}

// examples/weather/react-nano_kit/src/components/ForecastWeather.tsx
import { useMemo } from 'react'
import type { Weather } from 'data-layer/services/types'
import styles from './ForecastWeather.module.css'

export interface Props {
  weather: Weather
  mode: string
}

export function ForecastWeather({
  weather,
  mode
}: Props) {
  const weatherTime = useMemo(() => {
    const { date } = weather

    if (!date) {
      return ''
    }

    if (mode === 'hourly') {
      return date.toLocaleTimeString(undefined, {
        hour: 'numeric',
        minute: '2-digit'
      })
    }

    return date.toLocaleDateString(undefined, {
      day: 'numeric',
      month: 'short'
    })
  }, [weather, mode])

  return (
    <div className={styles.root}>
      <time
        className={styles.time}
        dateTime={weather.dateText}
      >
        {weatherTime}
      </time>
      <img
        className={styles.image}
        src={weather.icon}
        alt={weather.description}
      />
      <h3 className={styles.temp}>
        {weather.tempText}
      </h3>
      <p className={styles.description}>
        {weather.description}
      </p>
    </div>
  )
}
