// examples/weather/solid-nanostores/src/components/CityInput.tsx
import { useStore } from '@nanostores/solid'
import { For } from 'solid-js'
import {
  $locationSearch,
  $citySuggestions
} from 'data-layer/stores/location'
import styles from './CityInput.module.css'

export function CityInput() {
  const locationSearch = useStore($locationSearch)
  const citySuggestions = useStore($citySuggestions)

  return (
    <div class={styles.root}>
      <label
        class={styles.label}
        for='city'
      >
        Search for a city:
      </label>
      <input
        list='cities'
        id='city'
        type='text'
        name='city'
        class={styles.input}
        value={locationSearch()}
        onInput={e => $locationSearch.set(e.currentTarget.value)}
      />
      <datalist id='cities'>
        <For each={citySuggestions()}>
          {city => <option value={city.label}></option>}
        </For>
      </datalist>
    </div>
  )
}

// examples/weather/react-nanostores/src/components/CityInput.tsx
import { useCallback } from 'react'
import { useStore } from '@nanostores/react'
import {
  $locationSearch,
  $citySuggestions
} from 'data-layer/stores/location'
import styles from './CityInput.module.css'

export function CityInput() {
  const locationSearch = useStore($locationSearch)
  const citySuggestions = useStore($citySuggestions)
  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => $locationSearch.set(e.target.value),
    []
  )

  return (
    <div className={styles.root}>
      <label
        className={styles.label}
        htmlFor='city'
      >
        Search for a city:
      </label>
      <input
        list='cities'
        id='city'
        type='text'
        name='city'
        className={styles.input}
        value={locationSearch}
        onChange={handleChange}
      />
      <datalist id='cities'>
        {citySuggestions.map(city => (
          <option
            key={city.label}
            value={city.label}
          />
        ))}
      </datalist>
    </div>
  )
}
