// examples/weather/solid-nanostores/src/components/Weather.tsx
import { useStore } from '@nanostores/solid'
import { Show } from 'solid-js'
import { $currentWeather } from 'data-layer/stores/weather'
import styles from './Weather.module.css'

export function Weather() {
  const currentWeather = useStore($currentWeather)

  return (
    <Show when={currentWeather()}>
      <div class={styles.root}>
        <h3 class={styles.currentTemp}>
          {currentWeather()!.tempText}
        </h3>
        <img
          class={styles.image}
          src={currentWeather()!.icon}
          alt={currentWeather()!.description}
        />
        <p
          class={styles.feelsLike}
        >
          Feels like {currentWeather()!.feelsLikeText}
        </p>
        <p class={styles.description}>
          {currentWeather()!.description}
          <br />
          Humidity: {currentWeather()!.humidity}%
        </p>
      </div>
    </Show>
  )
}

// examples/weather/react-nanostores/src/components/Weather.tsx
import { useStore } from '@nanostores/react'
import { $currentWeather } from 'data-layer/stores/weather'
import styles from './Weather.module.css'

export function Weather() {
  const currentWeather = useStore($currentWeather)

  if (!currentWeather) {
    return null
  }

  return (
    <div className={styles.root}>
      <h3 className={styles.currentTemp}>
        {currentWeather.tempText}
      </h3>
      <img
        className={styles.image}
        src={currentWeather.icon}
        alt={currentWeather.description}
      />
      <p
        className={styles.feelsLike}
      >
        Feels like
        {' '}
        {currentWeather.feelsLikeText}
      </p>
      <p className={styles.description}>
        {currentWeather.description}
        <br/>
        Humidity:
        {' '}
        {currentWeather.humidity}
        %
      </p>
    </div>
  )
}
